### ISSUE TITLE
how to configure images?

### ISSUE THREAD

**Issue by fkgruber** [khoj-ai/khoj#338]
Hi 
How do you configure images search? I couldn't find any instruction and it is not an option in the gui

thanks
FKG

**Comment by debanjum** [comment]
We haven't exposed a GUI option to do this yet. So to index images for search, you can manually edit your `khoj.yml` (at `~/.khoj/khoj.yml`) to something like below:

```yaml
content_type:
  image:
    input-directories: /path/to/your/images/directory
    input-filter: null
    embeddings-file: "~/.khoj/content/image/image_embeddings.pt"
    batch-size: 50
    use-xmp-metadata: False
```
