### ISSUE TITLE
[FIX] fresh self-hosted instance fails to start up in k8s

### ISSUE THREAD

**Issue by asg0451** [khoj-ai/khoj#684]
## Describe the bug
A clear and concise description of what the bug is. Please include what you were expecting to happen vs. what actually happened.

fresh instance of Khoj fails to start up for the first time with the following error

```
            │ ❱  80 │   │   return executor(sq │
                           │    81 │                          │
                           │    82 │   def _execute(self, sql │
                           │    83 │   │   self.db.validate_n │
                           │                                  │
                           │ /usr/local/lib/python3.10/dist-p │
                           │ ackages/django/db/backends/utils │
                           │ .py:84 in _execute               │
                           │                                  │
                           │    81 │                          │
                           │    82 │   def _execute(self, sql │
                           │    83 │   │   self.db.validate_n │
                           │ ❱  84 │   │   with self.db.wrap_ │
                           │    85 │   │   │   if params is N │
                           │    86 │   │   │   │   # params d │
                           │    87 │   │   │   │   return sel │
                           │                                  │
                           │ /usr/local/lib/python3.10/dist-p │
                           │ ackages/django/db/utils.py:91 in │
                           │ __exit__                         │
                           │                                  │
                           │    88 │   │   │   │   # the conn │
                           │    89 │   │   │   │   if dj_exc_ │
                           │    90 │   │   │   │   │   self.w │
                           │ ❱  91 │   │   │   │   raise dj_e │
                           │    92 │                          │
                           │    93 │   def __call__(self, fun │
                           │    94 │   │   # Note that we are │
                           │                                  │
                           │ /usr/local/lib/python3.10/dist-p │
                           │ ackages/django/db/backends/utils │
                           │ .py:89 in _execute               │
                           │                                  │
                           │    86 │   │   │   │   # params d │
                           │    87 │   │   │   │   return sel │
                           │    88 │   │   │   else:          │
                           │ ❱  89 │   │   │   │   return sel │
                           │    90 │                          │
                           │    91 │   def _executemany(self, │
                           │    92 │   │   self.db.validate_n │
                           ╰──────────────────────────────────╯
                           IntegrityError: null value in column
                           "chat_model_id" of relation
                           "database_agent" violates not-null
                           constraint
                           DETAIL:  Failing row contains (1,
                           2024-03-31 22:27:31.683039+00,
                           2024-03-31 22:27:31.683052+00, Khoj,
                           You are Khoj, a smart, inquisitive
                           and helpful personal assistan...,
                           https://khoj-web-bucket.s3.amazonaws
                           .com/lamp-128.png, ["*"], t, t,
                           khoj, null, null).
```

## To Reproduce

apply this k8s yaml
```
apiVersion: v1
kind: Namespace
metadata:
  name: khoj

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: khoj
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: database
          image: pgvector/pgvector:pg16
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
              name: psql
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data/
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path

# headless svc
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: khoj
spec:
  clusterIP: None
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: khoj
  namespace: khoj
spec:
  selector:
    matchLabels:
      app: khoj
  serviceName: khoj
  replicas: 1
  template:
    metadata:
      labels:
        app: khoj
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: khoj
          image: ghcr.io/khoj-ai/khoj:latest
          ports:
            - containerPort: 42110
              name: web
          volumeMounts:
            - name: config
              mountPath: /root/.khoj
            - name: models
              mountPath: /root/.cache/torch/sentence_transformers
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: database-0.database.khoj.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: KHOJ_DJANGO_SECRET_KEY
              value: secret
            - name: KHOJ_DEBUG
              value: "False"
            - name: KHOJ_ADMIN_EMAIL
              value: miles.frankel@gmail.com
            - name: KHOJ_ADMIN_PASSWORD
              value: password
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1"
          args:
            - --host="0.0.0.0"
            - --port=42110
            - -v
            - --anonymous-mode
  volumeClaimTemplates:
    - metadata:
        name: models
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
        storageClassName: local-path
    - metadata:
        name: config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
        storageClassName: local-path

```

## Platform
- Server:
    - [ ] Cloud-Hosted (https://app.khoj.dev)
    - [X] Self-Hosted Docker
    - [ ] Self-Hosted Python package
    - [ ] Self-Hosted source code
- Client:
    - [ ] Obsidian
    - [ ] Emacs
    - [ ] Desktop app
    - [ ] Web browser
    - [ ] WhatsApp
- OS:
    - [ ] Windows
    - [ ] macOS
    - [X] Linux
    - [ ] Android
    - [ ] iOS

### If self-hosted
- Server Version [e.g. 1.0.1]:
